# Generated by Django 5.2.11 on 2026-02-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GHLAuthCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=255, unique=True)),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                ("expires_in", models.IntegerField()),
                ("scope", models.TextField(blank=True, null=True)),
                ("user_type", models.CharField(blank=True, max_length=50, null=True)),
                ("company_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "location_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "timezone",
                    models.CharField(
                        blank=True, default="America/Chicago", max_length=100, null=True
                    ),
                ),
                (
                    "location_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "business_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "business_phone",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
