# Generated by Django 5.2.11 on 2026-03-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ghl_integration", "0002_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("data", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
