# Generated by Django 5.2.11 on 2026-02-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TranscriptionJobLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("media_url", models.URLField(max_length=2048)),
                (
                    "status",
                    models.CharField(
                        choices=[("in_progress", "In progress")],
                        db_index=True,
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("transcript", models.TextField(blank=True)),
                ("failure_reason", models.CharField(blank=True, max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Transcription job log",
                "verbose_name_plural": "Transcription job logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
