# Generated by Django 5.2.11 on 2026-03-01 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audio_analysis", "0001_initial"),
        ("ghl_integration", "0003_webhooklog"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranscriptionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("media_url", models.URLField(max_length=2048)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("transcribed", "Transcribed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                (
                    "transcript",
                    models.TextField(
                        blank=True, help_text="Full transcription of the audio."
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="Summary of the audio content."
                    ),
                ),
                ("failure_reason", models.CharField(blank=True, max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcription_logs",
                        to="ghl_integration.contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transcription log",
                "verbose_name_plural": "Transcription logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="TranscriptionJobLog",
        ),
    ]
