# Generated by Django 5.2.11 on 2026-03-02 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audio_analysis", "0002_transcriptionlog_delete_transcriptionjoblog"),
        ("audio_core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcriptionlog",
            name="audio_file",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transcription_logs",
                to="audio_core.audiofile",
            ),
            preserve_default=False,
        ),
    ]
