# Generated by Django 5.2.11 on 2026-02-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "openai_api_key",
                    models.CharField(
                        blank=True,
                        help_text="OpenAI API key for summarization and other AI features.",
                        max_length=255,
                    ),
                ),
                (
                    "openai_model",
                    models.CharField(
                        default="gpt-4o-mini",
                        help_text="Model name, e.g. gpt-4o-mini, gpt-4.",
                        max_length=64,
                    ),
                ),
                (
                    "rev_ai_access_token",
                    models.CharField(
                        blank=True,
                        help_text="Rev AI access token for transcription.",
                        max_length=255,
                    ),
                ),
                (
                    "summary_prompt",
                    models.TextField(
                        blank=True,
                        default="Summarize the following transcript of an appointment or call. Include: main topics, decisions, action items, and any follow-up needed.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "System settings",
                "verbose_name_plural": "System settings",
                "ordering": ["-created_at"],
            },
        ),
    ]
